"""initial_schema

Revision ID: 658d899f626f
Revises:
Create Date: 2026-07-16 01:28:32.080477
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "658d899f626f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_is_active"), "categories", ["is_active"], unique=False)
    op.create_table(
        "payment_channels",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("BINANCE_PAY", "MANUAL", name="paymentkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("settlement_currency", sa.String(length=8), nullable=False),
        sa.Column("units_per_usdt", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fee_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("min_credit", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("max_credit", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("instructions_ar", sa.Text(), nullable=False),
        sa.Column("account_label", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_payment_channels_is_active"), "payment_channels", ["is_active"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_is_blocked"), "users", ["is_blocked"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("public_code", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_code", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REVIEW_REQUIRED",
                "CONFIRMED",
                "REJECTED",
                "EXPIRED",
                name="paymentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("credit_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("credit_currency", sa.String(length=8), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("settlement_currency", sa.String(length=8), nullable=False),
        sa.Column("rate_snapshot", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fee_percent_snapshot", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("payer_reference", sa.String(length=200), nullable=True),
        sa.Column("proof_file_id", sa.String(length=300), nullable=True),
        sa.Column("checkout_url", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=300), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["channel_code"], ["payment_channels.code"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_code", "external_id", name="uq_payment_external"),
        sa.UniqueConstraint("public_code", name="uq_payment_public_code"),
    )
    op.create_index("ix_payment_review", "payments", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_payments_channel_code"), "payments", ["channel_code"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=180), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column(
            "fulfillment_mode",
            sa.Enum("AUTO", "MANUAL", name="fulfillmentmode", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("provider_code", sa.String(length=40), nullable=True),
        sa.Column("provider_product_id", sa.String(length=100), nullable=True),
        sa.Column("customer_input_label", sa.String(length=160), nullable=False),
        sa.Column("customer_input_pattern", sa.String(length=300), nullable=True),
        sa.Column("customer_input_help", sa.String(length=300), nullable=False),
        sa.Column("terms_ar", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_code", "provider_product_id", name="uq_provider_product"),
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_is_active"), "products", ["is_active"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "DEPOSIT",
                "PURCHASE",
                "REFUND",
                "ADMIN_CREDIT",
                "ADMIN_DEBIT",
                name="ledgerkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("reference_type", sa.String(length=40), nullable=False),
        sa.Column("reference_id", sa.String(length=80), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.user_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_ledger_idempotency_key"),
    )
    op.create_index(
        op.f("ix_ledger_entries_wallet_id"), "ledger_entries", ["wallet_id"], unique=False
    )
    op.create_index(
        "ix_ledger_wallet_created", "ledger_entries", ["wallet_id", "created_at"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("public_code", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_name_snapshot", sa.String(length=180), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("customer_input_encrypted", sa.Text(), nullable=False),
        sa.Column("delivery_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PROCESSING",
                "PROVIDER_PENDING",
                "REVIEW_REQUIRED",
                "COMPLETED",
                "FAILED",
                "REFUNDED",
                "CANCELED",
                name="orderstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_code", sa.String(length=40), nullable=True),
        sa.Column("provider_order_id", sa.String(length=120), nullable=True),
        sa.Column("provider_status", sa.String(length=80), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_message", sa.String(length=500), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_order_idempotency_key"),
        sa.UniqueConstraint("public_code", name="uq_order_public_code"),
    )
    op.create_index("ix_order_worker", "orders", ["status", "next_retry_at"], unique=False)
    op.create_index(op.f("ix_orders_product_id"), "orders", ["product_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_product_id"), table_name="orders")
    op.drop_index("ix_order_worker", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_ledger_wallet_created", table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_wallet_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_products_is_active"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_channel_code"), table_name="payments")
    op.drop_index("ix_payment_review", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_users_is_blocked"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_payment_channels_is_active"), table_name="payment_channels")
    op.drop_table("payment_channels")
    op.drop_index(op.f("ix_categories_is_active"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
