"""unique_manual_payment_reference

Revision ID: a66220d5e82a
Revises: 658d899f626f
Create Date: 2026-07-16 01:32:10.048473
"""

from collections.abc import Sequence

from alembic import op

revision: str = "a66220d5e82a"
down_revision: str | Sequence[str] | None = "658d899f626f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_payment_payer_reference", ["channel_code", "payer_reference"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_constraint("uq_payment_payer_reference", type_="unique")

    # ### end Alembic commands ###
